on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: cisamplesmasteracr.azurecr.io
        username: ${{ secrets.acr_cisamplesmasteracr_username }}
        password: ${{ secrets.acr_cisamplesmasteracr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t cisamplesmasteracr.azurecr.io/cisamples5c63:${{ github.sha }}
        docker push cisamplesmasteracr.azurecr.io/cisamples5c63:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cisamples_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cisamples5c63 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cisamples5c63`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cisamples5c63
        container-registry-url: cisamplesmasteracr.azurecr.io
        container-registry-username: ${{ secrets.acr_cisamplesmasteracr_username }}
        container-registry-password: ${{ secrets.acr_cisamplesmasteracr_password }}
        secret-name: cisamplesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: cisamples5c63
        manifests: |
          .devcontainer/manifests/deployment-5c63.yml
          .devcontainer/manifests/service-5c63.yml
          .devcontainer/manifests/ingress-5c63.yml
        images: |
          cisamplesmasteracr.azurecr.io/cisamples5c63:${{ github.sha }}
        imagepullsecrets: |
          cisamplesdockerauth